### PR TITLE
Fixed async issue using promises

### PR DESCRIPTION
**Pull request by psayre23**
This will work in node v0.12 and on. Will need a library for backwards compatibilty.

### CODE REVIEW

**Comment by jaredalexander** [comment]
Thanks for the quick fix. How can I utilize this? Inside my app.intent function, I have an async http request that talks to an API that returns JSON. On success, I parse the JSON and grab the result. I then call say("blah") and shouldEndSession(true), and lastly done(). However, node then crashes when I call done(). I get the following error:

TypeError: Cannot read property 'then' of null
(line 150 of your app.js)

Any help would be greatly appreciated, thanks!

**Comment by psayre23** [comment]
Ah! The problem is the promise doesn't exist yet. I'll take a quick look at
a fix.

~ Paul

**Comment by psayre23** [comment]
That should fix the issue. I was only testing it async, so I never saw it. Good catch.

**Comment by matt-kruse** [comment]
Thanks for the patch. I resolved this issue using Promises, but in a slightly different way. Update coming soon.

**Pull request closed without merging**
