### PR TITLE
AudioPlayer functionality

### PR DESCRIPTION
**Pull request by wschaeferiii**
Added Audioplayer functionality to the alexa-app library.

Simply write `response.audioPlayerPlay(url, token, playBehavior, offsetInMilliseconds, expectedPreviousToken)` and you can play long form audio URL requests with a given url and token.  `playBehavior` defaults to `"ENQUEUE_ALL"`, and `offsetInMilliseconds` defaults to 0, and `expectedPreviousToken` defaults to `undefined`.

Also, added is `response.audioPlayerStop()` and `response.audioPlayerClearQueue(clearBehavior)` where `clearBehavior` defaults to `"CLEAR_ALL"` .

The request's `context` object is required in long form audio requests since the session object is not included once the player begins playing, but is copied from the request's `session` object.

### CODE REVIEW

**Comment by wschaeferiii** [comment]
Alright, sorry for all the failed merges / coverage issues.

**Comment by chrisdeely** [comment]
@wschaeferiii Nice work here, exactly what I needed. You mentioned being able to play "long form audio", but I noticed that Alexa will continually loop a single section of an HLS live playlist instead of retrieving new segments. Have you experienced this? Are there additional flags to be set and/or intents to handle refreshing a live stream?

**Comment by wschaeferiii** [comment]
@chrisdeely Have you tried listening on the request with type `AudioPlayer.PlaybackNearlyFinished` sent from Alexa to your skill?  Here's the [Amazon documentation](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-audioplayer-interface-reference#playbacknearlyfinished-request) on it , however I am not sure on how to implement it into the library for easy use.

**Comment by dblock** [comment]
This looks good. It needs a README and CHANGELOG update, please.

**Comment by fremail** [comment]
@wschaeferiii Thank you for working on this! AudioPlayer interface is really useful!
Handling AudioPlayer events in `pre` isn't handy and the code is pretty messy.

What about adding a method like `app.intent` - `app.audioPlayer(event, func)` to handle the events: PlaybackStarted, PlaybackFinished, PlaybackStopped, PlaybackNearlyFinished, PlaybackFailed.

I imagine the code would be similar to `intent` implementation :)

**Comment by dblock** [comment]
@fremail I think that would be better. Want to try an alternate implementation?

**Comment by fremail** [comment]
@wschaeferiii Using code from your branch I got an error.

I have an app uploaded to Lambda.

The error is caused on getting `AudioPlayer` events. I got it twise: one for `AudioPlayer.PlaybackStarted` and one for `AudioPlayer.PlaybackFinished`.

```
{
    "errorMessage": "Cannot read property 'new' of undefined",
    "errorType": "TypeError",
    "stackTrace": [
        "new alexa.request (/var/task/node_modules/alexa-app/index.js:219:27)",
        "/var/task/node_modules/alexa-app/index.js:317:18",
        "tryCatcher (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/util.js:26:23)",
        "Promise._resolveFromResolver (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:483:31)",
        "new Promise (/var/task/node_modules/alexa-app/node_modules/bluebird/js/main/promise.js:71:37)",
        "request (/var/task/node_modules/alexa-app/index.js:316:10)",
        "handler (/var/task/node_modules/alexa-app/index.js:448:8)"
    ]
}
```

I logged the `event` in `this.handler` (index.js:447):
```
{ 
  version: '1.0', 
  context: { 
    AudioPlayer: { 
      offsetInMilliseconds: 731, 
      token: 'japanese_audio', 
      playerActivity: 'FINISHED' 
    }, 
    System: { 
      application: [Object], 
      user: [Object], 
      device: [Object] 
    } 
  }, 
  request: { 
    type: 'AudioPlayer.PlaybackFinished', 
    requestId: 'amzn1.echo-api.request.fa43da2e-9ea2-4149-bd47-3b077388e5e8', 
    timestamp: '2016-12-19T15:12:08Z', 
    locale: 'en-US', 
    token: 'japanese_audio', 
    offsetInMilliseconds: 731 
  } 
}
```

Though I think code from master has the same error.

**Comment by fremail** [comment]
It seems the problem is in this:

> The session object is included for all standard requests, but it is not included for AudioPlayer or PlaybackController requests.

[source](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference#request-body-parameters)

**Comment by dblock** [comment]
@fremail Will you finish this one up now that #91 is merged? Thanks!

**Comment by dblock** [comment]
Closed via https://github.com/matt-kruse/alexa-app/pull/92, thanks @fremail for finishing this!

**Pull request closed without merging**
